version: 2.1
jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.23.1-focal
    # Steps to the job
    working_directory: /tmp
    steps:
      - checkout
      - run: npm i -D @playwright/test
      - run: npx playwright install
      - run: npx playwright install chrome
      - run:
          name: Run test
          command: PLAYWRIGHT_JUNIT_OUTPUT_NAME=index.html npx playwright test --reporter=junit --project=chromium
      - run: 
          name: Creating artifact folder and storing files
          command: mkdir /tmp/artifacts
          command: cp playwright-report/index.html /tmp/artifacts
# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test